---

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"  # See documentation for possible values
    target-branch: release-2.0
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]

  - package-ecosystem: "github-actions"  # See documentation for possible values
    target-branch: release-2.1
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]

  - package-ecosystem: "github-actions"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]

  - package-ecosystem: "compposer"  # See documentation for possible values
    target-branch: release-2.0
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"  # See documentation for possible values
    target-branch: release-2.0
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "compposer"  # See documentation for possible values
    target-branch: release-2.1
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"  # See documentation for possible values
    target-branch: release-2.1
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
