---

name: Automatic update of assets

on:
  workflow_dispatch:
  schedule:
    # Run every week on Sunday at 00:00 AM UTC
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build assets
    runs-on: [ubuntu-latest]

    steps:
      - name: Run assets build
        uses: actions/github-script@v6
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-base',
              workflow_id: 'build-release.yml',
              ref: 'release-2.0'
            })
